In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
docs=pd.read_csv('example_train.csv')
docs.head()

Document      Class
0     Greatlakes is a great educational institution.  education
1            Educational greatness depends on ethics  education
2  A story of great ethics and educational greatness  education
3                           Sholey is a great cinema     cinema
4                   good movie depends on good story     cinema

In [3]:
# coverting the label to numberical variable
docs['Class']=docs.Class.map({'cinema':0,'education':1})
docs

Document  Class
0     Greatlakes is a great educational institution.      1
1            Educational greatness depends on ethics      1
2  A story of great ethics and educational greatness      1
3                           Sholey is a great cinema      0
4                   good movie depends on good story      0

In [4]:
numpy_array=docs.as_matrix()
X=numpy_array[:,0]
Y=numpy_array[:,1]
Y=Y.astype('int')
print('X')
print(X)
print('Y')
print(Y)

X
['Greatlakes is a great educational institution.'
 'Educational greatness depends on ethics'
 'A story of great ethics and educational greatness'
 'Sholey is a great cinema' 'good movie depends on good story']
Y
[1 1 1 0 0]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [5]:
#create a object of CountVectorizer() class
from sklearn.feature_extraction.text import CountVectorizer
vec=CountVectorizer()

In [6]:
vec.fit(X)
vec.vocabulary_

{'greatlakes': 7,
 'is': 10,
 'great': 6,
 'educational': 3,
 'institution': 9,
 'greatness': 8,
 'depends': 2,
 'on': 13,
 'ethics': 4,
 'story': 15,
 'of': 12,
 'and': 0,
 'sholey': 14,
 'cinema': 1,
 'good': 5,
 'movie': 11}

In [7]:
#Removing the stop word
vec=CountVectorizer(stop_words='english')
vec.fit(X)
vec.vocabulary_

{'greatlakes': 6,
 'great': 5,
 'educational': 2,
 'institution': 8,
 'greatness': 7,
 'depends': 1,
 'ethics': 3,
 'story': 11,
 'sholey': 10,
 'cinema': 0,
 'good': 4,
 'movie': 9}

In [8]:
#printing the feature names 
print(vec.get_feature_names())
print(len(vec.get_feature_names()))

['cinema', 'depends', 'educational', 'ethics', 'good', 'great', 'greatlakes', 'greatness', 'institution', 'movie', 'sholey', 'story']
12


In [9]:
x_transformed=vec.transform(X)
x_transformed
print(x_transformed)

  (0, 2)	1
  (0, 5)	1
  (0, 6)	1
  (0, 8)	1
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (1, 7)	1
  (2, 2)	1
  (2, 3)	1
  (2, 5)	1
  (2, 7)	1
  (2, 11)	1
  (3, 0)	1
  (3, 5)	1
  (3, 10)	1
  (4, 1)	1
  (4, 4)	2
  (4, 9)	1
  (4, 11)	1


In [10]:
#converting transformed matrix back to an array
#note the high number of zeros
X=x_transformed.toarray()
X

array([[0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

In [11]:
#converting matrix to dataframe
pd.DataFrame(X,columns=vec.get_feature_names())

cinema  depends  educational  ethics  good  great  greatlakes  greatness  \
0       0        0            1       0     0      1           1          0   
1       0        1            1       1     0      0           0          1   
2       0        0            1       1     0      1           0          1   
3       1        0            0       0     0      1           0          0   
4       0        1            0       0     2      0           0          0   

   institution  movie  sholey  story  
0            1      0       0      0  
1            0      0       0      0  
2            0      0       0      1  
3            0      0       1      0  
4            0      1       0      1

In [12]:
#Reading the test documents
test_docs=pd.read_csv('example_test.csv')

In [13]:
# coverting the label to numberical variable
test_docs['Class']=test_docs.Class.map({'cinema':0,'education':1})
test_docs

Document  Class
0  very good educational institution      1

In [14]:
numpy_array=test_docs.as_matrix()
X_test=numpy_array[:,0]
Y_test=numpy_array[:,1]
Y_test=Y.astype('int')
print('X_test')
print(X_test)
print('Y_test')
print(Y_test)

X_test
['very good educational institution']
Y_test
[1 1 1 0 0]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [15]:
#another way of representing the feature
X_test_transformed=vec.transform(X_test)
X_test_transformed
# print(x_transformed)

<1x12 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [16]:
#converting transformed matrix back to an array
#note the high number of zeros
X_test=X_test_transformed.toarray()
X_test

array([[0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0]], dtype=int64)

# Multinominal Naive Bayes

In [17]:
#buliding a multinominal NB model
from sklearn.naive_bayes import MultinomialNB

#instantiate NB class
mnb=MultinomialNB()
mnb.fit(X,Y)
#predicting probabilities of test data
mnb.predict_proba(X_test)

array([[0.32808399, 0.67191601]])

# Bernoulli Naive Bayes

In [20]:
from sklearn.naive_bayes import BernoulliNB

#instantiating bernoulli NB class
bnb=BernoulliNB()

#fitting the model
bnb.fit(X,Y)
bnb.predict(X_test)
bnb.predict_proba(X_test)

array([[0.2326374, 0.7673626]])